config/routes.rb
Rails.application.routes.draw do


  get 'page/index'
  get 'page/show'
  get 'page/new'
  get 'page/edit'
  get 'page/delete'
root 'subjects#index'

  resources :subjects do
    member do
      get :delete
    end
  end











 # get ':controller(/:action(/:id))'#default rout
  #root 'demo#index'
   #root Rout
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/page.rb
class Page < ApplicationRecord

  belongs_to :subject

validates :subject_id ,presence: true
validates :name ,presence: true
validates :peralink ,presence: true
validates :position ,presence: true

  scope :visible_subjects, lambda {where(:visible => true)}
  scope :invisible_subjects, lambda {where(:visible => false)}
  scope :sorted, lambda {order("position ASC")}
  scope :newest_first, lambda {order("created_at DESC")}
  scope :search, lambda {|query| where(["name LIKE ?","%#{query}%"])}


end

app/models/section.rb
class Section < ApplicationRecord

validates :page_id ,presence: true
validates :name ,presence: true
validates :position ,presence: true

validates :content_type ,presence: true
validates :content ,presence: true
end

app/models/subject.rb
class Subject < ApplicationRecord

has_many :pages

 validates :name ,presence: true
 validates :position ,presence: true


  scope :visible_subjects, lambda {where(:visible => true)}
  scope :invisible_subjects, lambda {where(:visible => false)}
  scope :sorted, lambda {order("position ASC")}
  scope :search, lambda {|query| where(["name LIKE ?","%#{query}%"])}

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  layout false
  def index
    @pages = Page.sorted
  end

  def show
    @page = Page.find(params[:id])
  end

  def new
    @page = Page.new
  end

  def create
    @page= Page.new(page_params)
    if @page.save
      flash[:notice] ="Page created successfully......"
      redirect_to(pages_path)
    else
      render('new')
    end
  end

  def edit
    @page = Page.find(params[:id])
  end

  def update
    @page = Page.find(params[:id])

    if @page.update_attributes(page_params)
      flash[:notice] ="Page updated successfully......"
      redirect_to(page_path(@page))
    else
      render('edit')
    end
  end

  def delete
    @page = Page.find(params[:id])
  end
  def destroy
    @page = Page.find(params[:id])
    @page.destroy
    flash[:notice] ="Page '#{@page.name}' delete successfully......"
    redirect_to(pages_path)
  end
  private
  def page_params
    params.required(:page).permit(:subject_id,:name,:position,:visible,:permalink)
  end


end

app/controllers/subjects_controller.rb
class SubjectsController < ApplicationController

  def index
    @subjects =Subject.sorted

  end

  def show
    @subject = Subject.find(params[:id])
  end

  def new
    @subject = Subject.new({:name => 'Default'})
  end

  def create
    @subject= Subject.new(subject_params)
    if @subject.save
      flash[:notice] ="Subject created successfully......"
      redirect_to(subjects_path)
    else
      render('new')
    end

  end


  def edit
    @subject = Subject.find(params[:id])
  end
  def update
    @subject = Subject.find(params[:id])

    if @subject.update_attributes(subject_params)
      flash[:notice] ="Subject updated successfully......"
      redirect_to(subject_path(@subject))
    else
      render('edit')
    end
  end

  def delete

    @subject = Subject.find(params[:id])
  end
  def destroy
    @subject = Subject.find(params[:id])
    @subject.destroy
    flash[:notice] ="Subject '#{@subject.name}' delete successfully......"
    redirect_to(subjects_path)
  end
  private
  def subject_params
    params.required(:subject).permit(:name,:position,:visible)
  end




end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/demo_helper.rb
module DemoHelper
end

app/helpers/page_helper.rb
module PageHelper
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/views/demo/hello.html.erb
<h2>this is hello in hello file</h2>

app/views/demo/index.html.erb
<h1>Hello This is my sample page</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Sample</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/delete.html.erb
<%= link_to("BACK TO LIST", pages_path, :class => 'back-link')%>
<div class="Page delete">
  <h1>Delete Subject</h1>
  <%= form_for(@page,:url => page_path(@page),:method => 'delete')do |f| %>
  <p>Are you sure you want to delete this page </p>
  <p class="reference-name"><%= @page.name%></p>


  <div class="form-buttons">
    <%= f.submit("Delete Page")%>
  </div>
  <%end%>
</div>

app/views/pages/edit.html.erb
<%= link_to("BACK TO LIST", pages_path, :class => 'back-link')%>
<div class="pages new">
  <h1>Update Page</h1>
  <%= form_for(@page,:url => page_path(@page),:method => 'patch')do |f| %>
  <table summary="Page for fields">
    <tr>
      <th>Name</th>
      <td><%= f.text_field(:name)%></td>
    </tr>
    <tr>
      <tr>
        <th>Subject ID</th>
        <td><%= f.text_field(:subject_id)%></td>
      </tr>

      <tr>
        <th>Permalink</th>
        <td><%= f.text_field(:permalink)%></td>
      </tr>

      <th>Position</th>
      <td><%= f.text_field(:position)%></td>
    </tr>
    <tr>
      <th>Visible</th>
      <td><%= f.text_field(:visible)%></td>
    </tr>
  </table>
  <div class="form-buttons">
    <%= f.submit("Update Page")%>
  </div>
  <%end%>
</div>

app/views/pages/index.html.erb
<div class="pages index">
  <h1>Pages</h1>
  <%= link_to("Add new Page",'pages/new',:class => 'action new')%>
  <table class="listing" summary="Page list">
    <tr class="header">
      <th>#</th>
      <th>Subject ID</th>
      <th>Page</th>
      <th>Permalink</th>
      <th>Visible</th>

      <th>Acton</th>
    </tr>
    <% @pages.each do |page|%>
    <tr>
      <td><%= page.position %></td>
      <td><%= page.subject_id %></td>
      <td><%= page.name %></td>
      <td><%= page.permalink %></td>
      <td class="center"><%= page.visible ? 'Yes':'No'%></td>

      <td class = "action">
        <%=link_to("Show",page_path(page),:class=>'acton show')%>
        <%=link_to("Edit",edit_page_path(page),:class=>'acton edit')%>
        <%=link_to("Delete",delete_page_path(page),:class=>'acton delete')%>
      </td>
    </tr>
    <%end%>
  </table>





</div>

app/views/pages/new.html.erb
<%= link_to("BACK TO LIST", pages_path, :class => 'back-link')%>
<div class="Page new">
  <h1>Create Page</h1>
  <%= form_for(@page,:url => pages_path,:method => 'post')do |f| %>
  <table summary="Page for fields">
    <tr>
      <th>Name</th>
      <td><%= f.text_field(:name)%></td>
    </tr>
    <tr>
      <th>Subject ID</th>
      <td><%= f.text_field(:subject_id)%></td>
    </tr>

    <tr>
      <th>Permalink</th>
      <td><%= f.text_field(:permalink)%></td>
    </tr>


    <tr>
      <th>Position</th>
      <td><%= f.text_field(:position)%></td>
    </tr>
    <tr>
      <th>Visible</th>
      <td><%= f.text_field(:visible)%></td>
    </tr>
  </table>
  <div class="form-buttons">
    <%= f.submit("Create Page")%>
  </div>
  <%end%>
</div>

app/views/pages/show.html.erb
<%= link_to("BACK TO LIST", pages_path, :class => 'back-link')%>
<div class="sujects show">
  <h1>Show Page</h1>
  <table summary="Page detail view">
    <tr>
      <th>Name</th>
      <td><%= @page.name %></td>
    </tr>
    <tr>
      <tr>
        <th>Subject ID</th>
        <td><%=  @page.subject_id %></td>
      </tr>

      <tr>
        <th>Permalink</th>
        <td><%=  @page.permalink %></td>
      </tr>

      <th>Position</th>
      <td><%= @page.position %></td>
    </tr>
    <tr>
      <th>Visible</th>
      <td><%= @page.visible ? 'true' : 'false' %></td>
    </tr>
    <tr>
      <th>Created</th>
      <td><%= @page.created_at %></td>
    </tr>
    <tr>
      <th>Updated</th>
      <td><%= @page.updated_at %></td>
    </tr>
  </table>
</div>

app/views/subjects/delete.html.erb
<%= link_to("BACK TO LIST", subjects_path, :class => 'back-link')%>
<div class="subject delete">
  <h1>Delete Subject</h1>
  <%= form_for(@subject,:url => subject_path(@subject),:method => 'delete')do |f| %>
  <p>Are you sure you want to delete this subject </p>
  <p class="reference-name"><%= @subject.name%></p>


  <div class="form-buttons">
    <%= f.submit("Delete Subject")%>
  </div>
  <%end%>
</div>

app/views/subjects/edit.html.erb
<%= link_to("BACK TO LIST", subjects_path, :class => 'back-link')%>
<div class="subject new">
  <h1>Update Subject</h1>
  <%= form_for(@subject,:url => subject_path(@subject),:method => 'patch')do |f| %>
  <table summary="Subject for fields">
    <tr>
      <th>Name</th>
      <td><%= f.text_field(:name)%></td>
    </tr>
    <tr>
      <th>Position</th>
      <td><%= f.text_field(:position)%></td>
    </tr>
    <tr>
      <th>Visible</th>
      <td><%= f.text_field(:visible)%></td>
    </tr>
  </table>
  <div class="form-buttons">
    <%= f.submit("Update Subject")%>
  </div>
  <%end%>
</div>

app/views/subjects/index.html.erb
<% if !flash[:notice].blank?%>
<div class ="notice">
  <%= flash[:notice] %>
</div>
<%end%>



<div class="subjects index">
  <h1>Subjects</h1>
  <%= link_to("Add new Subject",'subjects/new',:class => 'action new')%>
  <table class="listing" summary="Subject list">
    <tr class="header">
      <th>#</th>
      <th>Subject</th>
      <th>Visible</th>
      <th>Pages</th>
      <th>Acton</th>
    </tr>
    <% @subjects.each do |subject|%>
    <tr>
      <td><%= subject.position %></td>
      <td><%= subject.name %></td>
      <td class="center"><%= subject.visible ? 'Yes':'No'%></td>
      <td class="center"><%= subject.pages.size%></td>
      <td class = "action">
        <%=link_to("Show",subject_path(subject.id),:class=>'acton show')%>
        <%=link_to("Edit",edit_subject_path(subject.id),:class=>'acton edit')%>
        <%=link_to("Delete",delete_subject_path(subject.id),:class=>'acton delete')%>
      </td>
    </tr>
    <%end%>
  </table>

app/views/subjects/new.html.erb
<%= link_to("BACK TO LIST", subjects_path, :class => 'back-link')%>
<div class="subject new">
  <h1>Create Subject</h1>
  <%= form_for(@subject,:url => subjects_path,:method => 'post')do |f| %>
  <table summary="Subject for fields">
    <tr>
      <th>Name</th>
      <td><%= f.text_field(:name)%></td>
    </tr>
    <tr>
      <th>Position</th>
      <td><%= f.text_field(:position)%></td>
    </tr>
    <tr>
      <th>Visible</th>
      <td><%= f.text_field(:visible)%></td>
    </tr>
  </table>
  <div class="form-buttons">
    <%= f.submit("Create Subject")%>
  </div>
  <%end%>
</div>

app/views/subjects/show.html.erb
<% if !flash[:notice].blank?%>
<div class ="notice">
  <%= flash[:notice] %>
</div>
<%end%>



<%= link_to("BACK TO LIST", subjects_path, :class => 'back-link')%>
<div class="sujects show">
  <h1>Show Subject</h1>
  <table summary="Subject detail view">
    <tr>
      <th>Name</th>
      <td><%= @subject.name %></td>
    </tr>
    <tr>
      <th>Position</th>
      <td><%= @subject.position %></td>
    </tr>
    <tr>
      <th>Visible</th>
      <td><%= @subject.visible ? 'true' : 'false' %></td>
    </tr>
    <tr>
      <th>Created</th>
      <td><%= @subject.created_at %></td>
    </tr>
    <tr>
      <th>Updated</th>
      <td><%= @subject.updated_at %></td>
    </tr>
  </table>
</div>